name: .NET Pre Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 21
          extra_plugins: |
            semantic-release-net
          branches: |
            [
              {
                "name": "main",
                "prerelease": true
              }
            ]
        env:
          DEBUG: semantic-release:*
          NUGET_API_KEY: ${{ secrets.NUGET_KEY }}
          GH_NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
