name: Sync Release Branch

on: [workflow_dispatch]

jobs:
  merge-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Rebase release on master
        run: |
          git checkout master
          git pull
          git checkout release
          git pull
          git rebase master
          git push origin release
