name: Sync Release Branch

on: [workflow_dispatch]

jobs:
  merge-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git config pull.ff only
      - name: Push master to release branch
        run: |
          git checkout master
          git pull
          git checkout release
          git pull
          git merge --ff-only master
          git push
